steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.api', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/findash/api:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/findash/api:latest'
