packages:
  - 'apps/*'

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  bcrypt: true
  '@prisma/engines': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: false
  '@scarf/scarf': false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
  - unrs-resolver
